<?php $escape = $this->plugin('escapeHtml'); ?>

<div class="assets">
  <?php foreach ($attachments as $attachment): ?>
    <?php $asset = $attachment['asset']; ?>
    <figure class="asset">
        <?php $assetImage = ($asset) ? $this->thumbnail($asset, 'square') : ''; ?>
        <?php $page = (array_key_exists('page', $attachment)) ? $attachment['page'] : null; ?>
        <?php if ($page): ?>
            <a href="<?php echo $escape($page->siteUrl()); ?>">
                <?php echo $assetImage; ?>
            </a>
        <?php else: ?>
            <?php echo $assetImage; ?>
        <?php endif; ?>
        <?php if ($attachment['caption'] !== '' || $attachment['alt_link_title'] !== ''): ?>
        <figcaption class="caption">
            <?php if ($page): ?>
                <a href="<?php echo $escape($page->siteUrl()); ?>">
                    <?php $altLinkTitle = ($attachment['alt_link_title'] !== '') ? $escape($attachment['alt_link_title']) : false; ?>
                    <span class="link-title"><?php echo ($altLinkTitle) ? $altLinkTitle : $escape($page->title()); ?></span>
                </a>
            <?php endif; ?>
            <?php echo $escape($attachment['caption']); ?>
        </figcaption>
        <?php endif; ?>
    </figure>
  <?php endforeach; ?>
</div>
