<?php
$escAttr = $this->plugin('escapeHtmlAttr');

$siteTitle = $site->title();
$userBar = $this->userBar();

$primaryColor = $this->themeSetting('primary_color') ?? '#f3c03a';
$secondaryColor = $this->themeSetting('secondary_color') ?? '#261504';
$tertiaryColor = $this->themeSetting('tertiary_color') ?? '#d68f71';
$complementaryColor = $this->themeSetting('complementary_color') ?? '#e8e2dd';
$accentColor = $this->themeSetting('accent_color') ?? '#b15027';

$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');

if ($userBar) {
    $this->htmlElement('body')->appendAttribute('class', 'user-bar');
}

$page_template = isset($page) ? $page->layoutDataValue('template_name') : '';

$mainContentClass = strpos($page_template, 'full-width') === 0 ? 'fullwidth-container' : 'container';
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <style media="screen">
			:root {
				--primary: <?php echo $primaryColor; ?>;
				--primary-dark: <?php echo $this->ShadeColor($primaryColor, -10); ?>;
				--primary-contrast: <?php echo $this->ContrastColor($primaryColor, ['#fff', '#333']); ?>;
				--secondary: <?php echo $secondaryColor; ?>;
				--secondary-dark: <?php echo $this->ShadeColor($secondaryColor, -10); ?>;
				--secondary-contrast: <?php echo $this->ContrastColor($secondaryColor, ['#fff', '#333']); ?>;
                --tertiary: <?php echo $tertiaryColor; ?>;
				--tertiary-dark: <?php echo $this->ShadeColor($tertiaryColor, -10); ?>;
				--tertiary-contrast: <?php echo $this->ContrastColor($tertiaryColor, ['#fff', '#333']); ?>;
                --complementary: <?php echo $complementaryColor; ?>;
				--complementary-contrast: <?php echo $this->ContrastColor($complementaryColor, ['#fff', '#333']); ?>;
				--accent: <?php echo $accentColor; ?>;
				--accent-dark: <?php echo $this->ShadeColor($accentColor, -20); ?>;
                --accent-contrast: <?php echo $this->ContrastColor($accentColor, ['#fff', '#333']); ?>;
			}
		</style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>

        <?php echo $this->partial('common/header', ['userBar' => $userBar, 'site' => $site]); ?>

        <?php if (strpos($page_template, 'page-with-hero') === 0): ?>
            <?php echo $this->partial('common/banner'); ?>
        <?php endif; ?>

        <div id="content" class="<?php echo $escAttr($mainContentClass); ?>" role="main" tabindex="-1">
            <?php echo $this->content; ?>
        </div>

        <?php echo $this->partial('common/footer'); ?>

        <?php
        echo $this->inlineScript()
            ->prependFile($this->assetUrl('js/navigation.js'))
            ->prependFile($this->assetUrl('js/script.js'));
        ?>
    </body>
</html>
